language: node_js
cache: npm
node_js:
  - stable
script:
  - npm run build
deploy:
  - provider: pages
    target-branch: gh-pages
    local_dir: dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
